// src/components/Bar.tsx
import { motion } from 'motion/react'

interface link {
    id: number
    n: string
    h: string
}

const Data: link[] = [
    { id: 1, n: 'PIXIV', h: 'https://www.pixiv.net/en/users/73130815' },
    { id: 2, n: 'X', h: 'https://x.com/souljpg_' },
    { id: 3, n: 'KOFI', h: 'https://ko-fi.com/soul111' }
]

function Bar() {
    return (
        <div className='bg-c-black subpixel-antialiased top-0 w-screen h-11 font-display text-sm font-medium flex justify-between items-center pl-10 pr-10'>
            <h1 className='text-c-white'>SOULJPG</h1>
            <div className='text-c-white space-x-5'>
                {Data.map((ls) => (
                    <motion.a
                        key={ls.id}
                        href={ls.h}
                        target='_blank'
                        rel='noopener noreferrer'
                        whileHover={{ opacity: 0.5 }}
                        transition={{ duration: 0.5 }}
                    >
                        {ls.n}
                    </motion.a>
                ))
                }
            </div>
        </div>
    )
}
export default Bar

// src/components/Bar.vue
<script setup>
import { motion } from 'motion-v'

const links = [
    { id: 1, n: 'artstation', url: 'https://www.artstation.com/souljpg' },
    { id: 2, n: 'pixiv', url: 'https://www.pixiv.net/en/users/73130815' },
    { id: 3, n: 'x', url: 'https://x.com/souljpg_' },
    { id: 4, n: 'kofi', url: 'https://ko-fi.com/soul111' }
]
</script>

<template>
    <div class="bg-black/80 w-screen h-14 fixed top-0 z-40 flex justify-between items-center pl-5 pr-5">
        <div class="text-white leading-0.5">
            <h1 class="text-3xl font-eb">souljpgart</h1>
        </div>
        <div class="text-white space-x-3 select-none font-dm">
            <motion.a 
            v-for="link in links"
            :key="link.id"
            :href="link.url"
            target="_blank"
            rel="noopener noreferrer"
            :whileHover="{ opacity: 0.5 }"
            :transition="{ duration: 0.2 }"
            >
            {{ link.n }}
            </motion.a>
        </div>
    </div>
</template>
